### ISSUE TITLE
Error: mdast-util-definitions expected node

### ISSUE THREAD

**Issue by yordis** [mattjennings/remark-reading-time#1]
Getting the following issue:

```text
Server Error
Error: mdast-util-definitions expected node

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
definitions
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/remark-rehype/node_modules/mdast-util-definitions/index.js (20:11)
factory
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/index.js (123:18)
toHast
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/remark-rehype/node_modules/mdast-util-to-hast/lib/index.js (221:13)
<unknown>
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/remark-rehype/index.js (62:20)
wrapped
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/trough/index.js (111:16)
next
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/trough/index.js (62:23)
done
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/trough/index.js (145:7)
then
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/trough/index.js (155:5)
wrapped
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/trough/index.js (133:9)
next
file:///Users/ubi/Developer/StrawHat/adr/website/node_modules/trough/index.js (62:23)
```

![Screen Shot 2021-11-07 at 5 48 07 AM](https://user-images.githubusercontent.com/4237280/140641849-c078ac9e-4f05-41d4-967c-f224688f17a8.png)

**Comment by mattjennings** [comment]
Can you add a link to a reproduction? Either a repository or something like codesandbox

**Comment by yordis** [comment]
@mattjennings https://github.com/straw-hat-team/adr/blob/3184be9eaef7c56e9162b12249094c6d781a7be2/website/src/pages/adrs/%5Bslug%5D.tsx#L37 brach out to `yordis/add-website` branch

**Comment by mattjennings** [comment]
Ah, you just need to call the plugin as a function first. i.e `remarkReadingTime()`

**Comment by yordis** [comment]
@mattjennings 🤦🏻  I am sorry man, most plugins dont do the closure and I assumed things, my bad

**Comment by mattjennings** [comment]
No worries, I realized it's probably against the remark plugin standard. Maybe in a future update I'll switch it up so it follows that.

**Comment by yordis** [comment]
@mattjennings yeah, I can't follow the standard, such as;

```ts
[remarkReadingTime, { attribute: 'pepeg' }],
```

That would break.

Are you open to fix that? Maybe I can add some TypeScript in the mid-time as well

**Comment by yordis** [comment]
Also, what about adding `mdx` support to the package?

For example, https://github.com/stefanprobst/rehype-extract-toc/blob/main/src/mdx.js

**Comment by mattjennings** [comment]
I've not used MDX so I'm probably not the one to add support for it, but I would accept a PR!
